//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominatorHouseCore {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DominatorHouseCore.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a&apos;isha
        ///a&apos;ishah
        ///aa&apos;isha
        ///aa&apos;ishah
        ///aabha
        ///aabriella
        ///aachal
        ///aada
        ///aadhira
        ///aadhya
        ///aadila
        ///aadison
        ///aaditri
        ///aadrika
        ///aadvika
        ///aadya
        ///aaeedah
        ///aaeesha
        ///aafia
        ///aafiya
        ///aafiyah
        ///aafje
        ///aafreen
        ///aafrin
        ///aagot
        ///aahana
        ///aahliyah
        ///aahna
        ///aaila
        ///aailiyah
        ///aailyah
        ///aaima
        ///aaina
        ///aaira
        ///aairah
        ///aaisha
        ///aaishah
        ///aaiyana
        ///aaiza
        ///aaizah
        ///aaja
        ///aajah
        ///aajaylah
        ///aakanksha
        ///aakifa
        ///aakifah
        ///aakilah
        ///aakira
        ///aakiyah
        ///aakriti
        ///aala
        ///aalaa
        ///aalaiya
        ///aalaiyah
        ///aalana
        ///aalanah
        ///aalani
        ///aalaya
        ///aalayah
        ///aalayiah
        ///aalayjah
        ///aa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string femaleNames {
            get {
                return ResourceManager.GetString("femaleNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageResizer IsValidImage Image is not of JPEG format.
        /// </summary>
        public static string ImageResizer_IsValidImage_Image_is_not_of_JPEG_format_ {
            get {
                return ResourceManager.GetString("ImageResizer_IsValidImage_Image_is_not_of_JPEG_format_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InstaAcc EditPassword N_A.
        /// </summary>
        public static string InstaAcc_EditPassword_N_A {
            get {
                return ResourceManager.GetString("InstaAcc_EditPassword_N_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InstaAcc ScrapeItems Scraping items.
        /// </summary>
        public static string InstaAcc_ScrapeItems_Scraping_items {
            get {
                return ResourceManager.GetString("InstaAcc_ScrapeItems_Scraping_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InstagramScraper ScrapeMediaMaxId comments.
        /// </summary>
        public static string InstagramScraper_ScrapeMediaMaxId_comments {
            get {
                return ResourceManager.GetString("InstagramScraper_ScrapeMediaMaxId_comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InstagramScraper_ScrapeMediaMaxId_likes.
        /// </summary>
        public static string InstagramScraper_ScrapeMediaMaxId_likes {
            get {
                return ResourceManager.GetString("InstagramScraper_ScrapeMediaMaxId_likes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.j.
        ///aaban
        ///aabid
        ///aabraham
        ///aadam
        ///aadan
        ///aadarsh
        ///aaden
        ///aadesh
        ///aadham
        ///aadhav
        ///aadhavan
        ///aadhi
        ///aadhvik
        ///aadhyan
        ///aadi
        ///aadian
        ///aadil
        ///aadin
        ///aadish
        ///aadit
        ///aadith
        ///aadithya
        ///aaditya
        ///aadiv
        ///aadolf
        ///aadon
        ///aadrian
        ///aadrit
        ///aadvik
        ///aadyn
        ///aaenab
        ///aaftaab
        ///aaftab
        ///aagam
        ///aagand
        ///aagat
        ///aage
        ///aagman
        ///aahaan
        ///aahad
        ///aahan
        ///aahil
        ///aahim
        ///aahir
        ///aahron
        ///aaidan
        ///aaiden
        ///aaidyn
        ///aajad
        ///aajiv
        ///aajon
        ///aakar
        ///aakarsh
        ///aakas
        ///aakash
        ///aakeem
        ///aakib
        ///aalam
        ///aalap
        ///aali
        ///aalias
        ///aalijah
        ///aalim
        ///aalok
        ///aalon
        ///aaman
        ///a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string maleNames {
            get {
                return ResourceManager.GetString("maleNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Response Account Disabled.
        /// </summary>
        public static string Response_Response_Account_Disabled {
            get {
                return ResourceManager.GetString("Response_Response_Account_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Response Action Block.
        /// </summary>
        public static string Response_Response_Action_Block {
            get {
                return ResourceManager.GetString("Response_Response_Action_Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Response Cant like this picture.
        /// </summary>
        public static string Response_Response_Can_t_like_this_picture_ {
            get {
                return ResourceManager.GetString("Response_Response_Can_t_like_this_picture_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Response Checkpoint.
        /// </summary>
        public static string Response_Response_Checkpoint {
            get {
                return ResourceManager.GetString("Response_Response_Checkpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Response Incorrect Password.
        /// </summary>
        public static string Response_Response_Incorrect_Password {
            get {
                return ResourceManager.GetString("Response_Response_Incorrect_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Response Instagram checkpoint  account needs mobile verification.
        /// </summary>
        public static string Response_Response_Instagram_checkpoint__account_needs_mobile_verification_ {
            get {
                return ResourceManager.GetString("Response_Response_Instagram_checkpoint__account_needs_mobile_verification_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Response Instagram detected suspicious activity you need to verify your identity.
        /// </summary>
        public static string Response_Response_Instagram_detected_suspicious_activity__you_need_to_verify_your_identity_ {
            get {
                return ResourceManager.GetString("Response_Response_Instagram_detected_suspicious_activity__you_need_to_verify_your" +
                        "_identity_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Response Login session expired.
        /// </summary>
        public static string Response_Response_Login_session_expired {
            get {
                return ResourceManager.GetString("Response_Response_Login_session_expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Response Media not found.
        /// </summary>
        public static string Response_Response_Media_not_found_ {
            get {
                return ResourceManager.GetString("Response_Response_Media_not_found_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Response Not authorized to perform action skipping.
        /// </summary>
        public static string Response_Response_Not_authorized_to_perform_action__skipping___ {
            get {
                return ResourceManager.GetString("Response_Response_Not_authorized_to_perform_action__skipping___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Response Password Reset.
        /// </summary>
        public static string Response_Response_Password_Reset {
            get {
                return ResourceManager.GetString("Response_Response_Password_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Response Sentry Blocked.
        /// </summary>
        public static string Response_Response_Sentry_Blocked {
            get {
                return ResourceManager.GetString("Response_Response_Sentry_Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Response Suspicious Activity.
        /// </summary>
        public static string Response_Response_Suspicious_Activity {
            get {
                return ResourceManager.GetString("Response_Response_Suspicious_Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Response Thread not found.
        /// </summary>
        public static string Response_Response_Thread_not_found_ {
            get {
                return ResourceManager.GetString("Response_Response_Thread_not_found_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response_Response_Too_many_requests_made__waiting_a_few_minutes_before_retrying_.
        /// </summary>
        public static string Response_Response_Too_many_requests_made__waiting_a_few_minutes_before_retrying_ {
            get {
                return ResourceManager.GetString("Response_Response_Too_many_requests_made__waiting_a_few_minutes_before_retrying_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Response Two Factor login.
        /// </summary>
        public static string Response_Response_Two_Factor_login {
            get {
                return ResourceManager.GetString("Response_Response_Two_Factor_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Response Two Factor login Right click your account and enter auth code.
        /// </summary>
        public static string Response_Response_Two_Factor_login__Right_click_your_account_and_enter_auth_code_ {
            get {
                return ResourceManager.GetString("Response_Response_Two_Factor_login__Right_click_your_account_and_enter_auth_code_" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Response User not found.
        /// </summary>
        public static string Response_Response_User_not_found_ {
            get {
                return ResourceManager.GetString("Response_Response_User_not_found_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Response_Response_Username_Doesn_t_Exist {
            get {
                return ResourceManager.GetString("Response_Response_Username_Doesn_t_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Response Username Doesn t Exist.
        /// </summary>
        public static string Response_Response_Username_Doesn_t_Exist1 {
            get {
                return ResourceManager.GetString("Response_Response_Username_Doesn_t_Exist1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Response You are not logged in please log in again.
        /// </summary>
        public static string Response_Response_You_are_not_logged_in__please_log_in_again_ {
            get {
                return ResourceManager.GetString("Response_Response_You_are_not_logged_in__please_log_in_again_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Response Your account has been sentry blocked  Your IP account has been flagged  It is advised to stop botting.
        /// </summary>
        public static string Response_Response_Your_account_has_been_sentry_blocked__Your_IP_account_has_been_flagged__It_is_advised_to_stop_botting_ {
            get {
                return ResourceManager.GetString("Response_Response_Your_account_has_been_sentry_blocked__Your_IP_account_has_been_" +
                        "flagged__It_is_advised_to_stop_botting_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Response Your password has been reset  Surf to Instagram for instructions on getting your account back.
        /// </summary>
        public static string Response_Response_Your_password_has_been_reset__Surf_to_Instagram_for_instructions_on_getting_your_account_back_ {
            get {
                return ResourceManager.GetString("Response_Response_Your_password_has_been_reset__Surf_to_Instagram_for_instruction" +
                        "s_on_getting_your_account_back_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScrapingFilters GetFilterDetails Enter a hastag.
        /// </summary>
        public static string ScrapingFilters_GetFilterDetails_Enter_a_hastag {
            get {
                return ResourceManager.GetString("ScrapingFilters_GetFilterDetails_Enter_a_hastag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScrapingFilters GetFilterDetails Enter a Instagram url  https   www instagram com explore locations.
        /// </summary>
        public static string ScrapingFilters_GetFilterDetails_Enter_a_Instagram_url__https___www_instagram_com_explore_locations____ {
            get {
                return ResourceManager.GetString("ScrapingFilters_GetFilterDetails_Enter_a_Instagram_url__https___www_instagram_com" +
                        "_explore_locations____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScrapingFilters GetFilterDetails Enter a Instagram url  https://www.instagram.com/p.
        /// </summary>
        public static string ScrapingFilters_GetFilterDetails_Enter_a_Instagram_url__https___www_instagram_com_p____ {
            get {
                return ResourceManager.GetString("ScrapingFilters_GetFilterDetails_Enter_a_Instagram_url__https___www_instagram_com" +
                        "_p____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScrapingFilters GetFilterDetails Enter a username.
        /// </summary>
        public static string ScrapingFilters_GetFilterDetails_Enter_a_username {
            get {
                return ResourceManager.GetString("ScrapingFilters_GetFilterDetails_Enter_a_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScrapingFilters GetFilterDetails Enter a username and timespan   Username hour minute.
        /// </summary>
        public static string ScrapingFilters_GetFilterDetails_Enter_a_username_and_timespan___Username_hour_minute_ {
            get {
                return ResourceManager.GetString("ScrapingFilters_GetFilterDetails_Enter_a_username_and_timespan___Username_hour_mi" +
                        "nute_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScrapingFilters GetFilterDetails Enter a username.
        /// </summary>
        public static string ScrapingFilters_GetFilterDetails_EnteScrapingFilters_GetFilterDetails_Enter_a_username {
            get {
                return ResourceManager.GetString("ScrapingFilters_GetFilterDetails_EnteScrapingFilters_GetFilterDetails_Enter_a_use" +
                        "rname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aaren
        ///abia
        ///abiah
        ///abijah
        ///abimbola
        ///abiodun
        ///addison
        ///adebola
        ///adebowale
        ///adedayo
        ///adetokunbo
        ///adilet
        ///afon
        ///agam
        ///agrippa
        ///ah
        ///ailbhe
        ///ainsley
        ///akachi
        ///akira
        ///akpofure
        ///akuchi
        ///aldus
        ///alemayehu
        ///alex
        ///alexis
        ///alinafe
        ///almas
        ///almog
        ///alpha
        ///amandeep
        ///amardeep
        ///amarjeet
        ///amarni
        ///amets
        ///amez
        ///amor
        ///amore
        ///amour
        ///anah
        ///ananta
        ///andie
        ///andile
        ///andy
        ///anesu
        ///angel
        ///aoi
        ///apoorva
        ///apurva
        ///aquila
        ///arden
        ///ariel
        ///arlie
        ///armarni
        ///aruna
        ///arya
        ///ash
        ///ashanti
        ///ashley
        ///ashton
        ///aston
        ///atalyah
        ///athaliah
        ///athol
        ///atiya
        ///aubrey        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string unisexNames {
            get {
                return ResourceManager.GetString("unisexNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserAccountEditPasswordNotValue.
        /// </summary>
        public static string UserAccountEditPasswordNotValue {
            get {
                return ResourceManager.GetString("UserAccountEditPasswordNotValue", resourceCulture);
            }
        }
    }
}
